sst2 = ['Flat or one-dimensional characters.', 'Uninteresting cinematography.', 'Lack of tension-building scenes.', 'Lack of emotional impact.', 'Weak or poorly developed plot.', 'Incoherent storytelling.', 'Unconvincing dialogue.', 'Overuse of clichés.', 'Excessive use of exposition.', 'Unnatural or forced acting.', 'Lack of character development.', 'Inconsistent character motivations.', 'Unengaging opening sequence.', 'Predictable twists and turns.', 'Poor pacing.', 'Excessive use of special effects.', 'Uninspired costume design.', 'Inadequate world-building.', 'Lack of chemistry between actors.', 'Flat or unmemorable soundtrack.', 'Unconvincing CGI effects.', 'Unimpressive set design.', 'Lack of attention to detail.', 'Inconsistent tone or mood.', 'Poorly choreographed action scenes.', 'Unrealistic physics or science.', 'Lack of originality.', 'Underdeveloped subplots.', 'Unmotivated character actions.', 'Incomprehensible editing.', 'Excessive product placement.', 'Weak character relationships.', 'Unexplained plot holes.', 'Lack of humor or wit.', 'Disjointed narrative structure.', 'Unconvincing romantic subplots.', 'Predictable resolutions.', 'Underwhelming climax.', 'Overuse of jump scares.', 'Unmemorable cinematography.', 'Lack of visual style.', 'Inadequate use of symbolism.', 'Uninspiring costume choices.', 'Underdeveloped antagonists.', 'Unimpressive special effects.', 'Excessive runtime.', 'Weak character arcs.', 'Uninteresting dialogue delivery.', 'Inadequate character backstories.', 'Unrealistic character abilities.', 'Lack of suspenseful moments.', 'Overreliance on stereotypes.', 'Unengaging subplots.', 'Poorly executed social commentary.', 'Excessive use of profanity.', 'Weak or forgettable one-liners.', 'Unmotivated plot twists.', 'Overuse of shaky cam.', 'Inadequate attention to historical accuracy.', 'Unimpressive practical effects.', 'Lack of authentic cultural representation.', 'Underutilized supporting characters.', 'Unconvincing character transformations.', 'Inconsistent visual effects quality.', 'Poorly integrated green screen effects.', 'Unexplained or unresolved mysteries.', 'Lack of relevant social commentary.', 'Overuse of hand-held camera work.', 'Underwhelming special effects for the budget.', 'Unmemorable or distracting sound design.', 'Inadequate attention to period details.', 'Lack of meaningful character conflicts.', 'Overuse of CGI blood and gore.', 'Uninspiring character deaths.', 'Poorly integrated CGI creatures.', 'Unconvincing character relationships.', 'Ineffective use of flashbacks.', 'Lack of thematic depth.', 'Overuse of exposition through news broadcasts.', 'Underwhelming romantic chemistry.', 'Unmotivated character decisions.', 'Excessive focus on unnecessary subplots.', 'Poorly executed dream sequences.', 'Inadequate attention to practical effects.', 'Lack of clear goals or objectives.', 'Overuse of montages to convey time passage.', 'Unmemorable or generic location choices.', 'Uninspired lighting and color choices.', 'Poorly executed voice-over narration.', 'Excessive use of unnecessary flashbacks.', 'Unmotivated use of voice modulation.', 'Inconsistent sound quality.', 'Unconvincing environmental effects.', 'Overuse of distracting CGI crowd scenes.', 'Underwhelming character reactions to significant events.', 'Lack of believable consequences for character actions.', 'Excessive use of distracting symbolism.', 'Uninspired costume changes.', 'Inadequate attention to sound mixing.', 'Lack of attention to cultural or historical accuracy.', 'Overuse of overly melodramatic music.', 'Unmemorable or inappropriate song choices.', 'Poorly integrated product placement.', 'Ineffective use of celebrity cameos.', 'Engaging plot.', 'Strong character development.', 'Great humor.', 'Clever narrative structure.', 'Compelling cinematography.', 'Emotionally resonant performances.', 'Immersive world-building.', 'Intriguing plot twists.', 'Memorable soundtrack.', 'Well-executed action sequences.', 'Thought-provoking themes.', 'Strong chemistry between lead actors.', 'Awe-inspiring visual effects.', 'Believable dialogue.', 'Unique and well-developed characters.', 'Impressive costume design.', 'Visually stunning set design.', 'Emotional depth.', 'Strong direction.', 'Engaging dialogue.', 'Powerful storytelling.', 'Sharp editing.', 'Surprising plot developments.', 'Compelling character arcs.', 'Beautiful cinematography.', 'Relatable themes.', 'Authentic period details.', 'Heartwarming moments.', 'Dynamic pacing.', 'Outstanding production design.', 'Mesmerizing special effects.', 'Engaging dialogue.', 'Intriguing subplots.', 'Captivating visual style.', 'Well-choreographed fight scenes.', 'Impactful sound design.', 'Realistic special effects.', 'Clever humor.', 'Mysterious atmosphere.', 'Charming characters.', 'Compelling social commentary.', 'Stunning locations.', 'Touching relationships.', 'Unpredictable storyline.', 'Engaging dialogue.', 'Authentic historical accuracy.', 'Intriguing mysteries.', 'Heart-pounding suspense.', 'Engaging political intrigue.', 'Stellar ensemble cast.', 'Inventive visuals.', 'Emotional resonance.', 'Engaging music score.', 'Complex character motivations.', 'Immersive 3D effects.', 'Creative world-building.', 'Witty and clever dialogue.', 'Suspenseful plot twists.', 'Iconic and quotable lines.', 'Memorable one-liners.', 'Well-structured screenplay.', 'Impactful symbolism.', 'Stunning costumes.', 'Atmospheric lighting.', 'Powerful allegories.', 'Great chemistry between actors.', 'Character growth and development.', 'Intricate and interconnected storylines.', 'Compelling moral dilemmas.', 'Immersive soundscapes.', 'Realistic and relatable emotions.', 'Engaging social commentary.', 'Complex and multi-dimensional villains.', 'Stunning and exotic locations.', 'Touching and heartfelt moments.', 'Well-orchestrated suspense.', 'Seamless special effects integration.', 'Captivating visual metaphors.', 'Character-driven narratives.', 'Clever and unexpected humor.', 'Engaging character relationships.', 'Powerful and memorable quotes.', 'Stylish and unique costumes.', 'Gripping and tense atmosphere.', 'Compelling and relevant social issues.', 'Captivating and immersive world-building.', 'Iconic and unforgettable scenes.', 'Stellar and diverse ensemble cast.', 'Emotionally charged confrontations.', 'Visually striking and innovative effects.', 'Engaging and intricate subplots.', 'Inspirational and motivational themes.', 'Realistic and relatable character flaws.', 'Stunning and vivid cinematography.', 'Compelling and memorable score.', 'Dynamic and well-paced action sequences.', 'Intricate and clever narrative structure.', 'Unforgettable and heartwarming moments.', 'Captivating and layered character backstories.', 'Charming and lovable side characters.', 'Intense and high-stakes conflicts.', 'Engaging and thought-provoking symbolism.', 'Masterful and precise editing.', 'Surprising and satisfying resolutions']

yelpp = ['Overpriced.', 'Unappetizing food.', 'Unprofessional service.', 'broken products.', 'Stale ingredients.', 'Long wait times.', 'Small portions.', 'Undercooked dishes.', 'Food poisoning.', 'Rude staff.', 'Dirty dining area.', 'Incorrect order.', 'Unpleasant odors.', 'Lack of vegetarian options.', 'Overpriced repairs.', 'Incomplete repairs.', 'Poor customer service.', 'Delayed service.', 'Repeated issues.', 'High-pressure upselling.', 'Vehicle damage during service.', 'Unreliable mechanics.', 'Hidden fees.', 'Unavailability of loaner cars.', 'Poor craftsmanship.', 'Unresolved issues.', 'Excessive delays.', 'Unprofessional contractors.', 'Overcharging for materials.', 'Inaccurate quotes.', 'Lack of communication.', 'Messy work areas.', 'Low-quality materials used.', 'Ineffective pest control.', 'Outdated facilities.', 'Unfriendly staff.', 'Overcrowded venues.', 'Cancelled events without notice.', 'Poor sound quality.', 'Uncomfortable seating.', 'Long ticket lines.', 'Lack of entertainment options.', 'Overpriced tickets.', 'Unreliable scheduling.', 'Misdiagnosis.', 'Long wait times in the clinic.', 'Unprofessional staff.', 'Prescription errors.', 'Unsanitary conditions.', 'Lack of empathy from doctors.', 'Inaccurate medical bills.', 'Difficulty scheduling appointments.', 'Excessive billing charges.', 'Lack of follow-up care.', 'Dirty rooms.', 'Uncomfortable beds.', 'Noisy surroundings.', 'Unresponsive staff.', 'Hidden fees.', 'Overbooked reservations.', 'Outdated decor.', 'Lack of basic amenities.', 'Unreliable Wi-Fi.', 'Smelly rooms.', 'Excessive fees.', 'Hidden charges.', 'Poor investment advice.', 'Slow customer support.', 'Unreliable online banking.', 'Account errors.', 'Unhelpful tellers.', 'Deceptive practices.', 'Lack of transparency.', 'Unauthorized transactions.', 'Biased reporting.', 'Inaccurate information.', 'Poorly edited content.', 'Subscription billing issues.', 'Unresponsive customer support.', 'Slow content delivery.', 'Excessive ads.', 'Lack of diverse perspectives.', 'Subscription auto-renewal.', 'Content not as advertised.', 'Overpriced parking fees.', 'Lack of available spaces.', 'Unsafe parking areas.', 'Confusing signage.', 'Towing without warning.', 'Dirty parking lots.', 'Inadequate lighting.', 'No valet service.', 'Unattended parking booths.', 'Inefficient payment systems.', 'Poor quality fabrics.', 'Incorrect sizing.', 'Torn or damaged items.', 'Unresponsive customer service.', 'Long return processes.', 'Uncomfortable clothing.', 'Misleading product descriptions.', 'Overpriced items.', 'Lack of fashionable options.', 'Unattractive store layout.', 'Faulty hardware.', 'Defective software.', 'Poor battery life.', 'Overheating issues.', 'Lack of customer support.', 'Difficult warranty claims.', 'Outdated technology.', 'Unreliable products.', 'Incompatible accessories.', 'Lack of software updates.', 'Poor cleaning quality.', 'Missed areas during cleaning.', 'Unprofessional cleaning staff.', 'High prices for cleaning services.', 'Late arrivals for scheduled cleaning.', 'Broken or damaged items after cleaning.', 'Unresponsive customer service for cleaning issues.', 'Inconsistent cleaning schedules.', 'Use of harsh or toxic cleaning products.', 'Lack of attention to detail in cleaning.', 'Delicious food.', 'Outstanding service.', 'Great value for the price.', 'high quality products.', 'Attentive waitstaff.', 'Fresh ingredients.', 'Variety of menu options.', 'Beautiful presentation.', 'Clean and inviting ambiance.', 'Generous portion sizes.', 'Quick service.', 'Creative dishes.', 'Amazing flavors.', 'Perfectly cooked dishes.', 'Skilled mechanics.', 'Timely repairs.', 'Reasonable prices.', 'Good communication on progress.', 'High-quality parts used.', 'Honest assessments.', 'Well-maintained facility.', 'Efficient service.', 'Reliable results.', 'Detailed vehicle cleaning.', 'Prompt response to inquiries.', 'Professional and courteous staff.', 'Thorough inspections.', 'Transparent pricing.', 'Excellent craftsmanship.', 'Clean and tidy work area.', 'Respect for property.', 'Attention to detail.', 'Timely project completion.', 'Effective problem-solving.', 'Engaging performances.', 'Variety of entertainment options.', 'Interactive experiences.', 'Welcoming and friendly staff.', 'Great sound and lighting.', 'Good seating arrangements.', 'Memorable experiences.', 'Reasonable ticket prices.', 'Convenient location.', 'Exciting atmosphere.', 'Skilled and knowledgeable doctors.', 'Compassionate care.', 'Efficient appointment scheduling.', 'Clean and well-organized facility.', 'Thorough examinations.', 'Clear communication of diagnoses.', 'Modern medical equipment.', 'Short wait times.', 'Personalized treatment plans.', 'Empathetic nursing staff.', 'Comfortable beds.', 'Clean rooms and amenities.', 'Responsive concierge service.', 'Beautiful views.', 'Quiet and relaxing atmosphere.', 'Good breakfast options.', 'Convenient location.', 'Well-maintained grounds.', 'Efficient check-in/check-out process.', 'Quality toiletries.', 'Professional financial advice.', 'Transparent fee structure.', 'Quick and accurate transactions.', 'Personalized financial plans.', 'Responsive customer support.', 'Secure online banking.', 'Competitive interest rates.', 'Trustworthy recommendations.', 'Convenient branch locations.', 'Flexible account options.', 'Informative content.', 'Engaging storytelling.', 'Quality journalism.', 'Diverse coverage.', 'User-friendly website/apps.', 'Timely news updates.', 'Impartial reporting.', 'Interactive features.', 'Engaging podcasts.', 'Clear and concise writing.', 'Ample parking space.', 'Well-maintained parking areas.', 'Good lighting for safety.', 'Clear signage for directions.', 'Affordable parking rates.', 'Secure parking facilities.', 'Accessible parking for all.', 'Easy entry and exit process.', 'Valet parking option.', 'Quick response to assistance requests.', 'Trendy and fashionable items.', 'High-quality materials.', 'Wide range of sizes available.', 'Helpful and stylish staff.', 'Great fitting rooms.', 'Reasonable prices for quality.', 'Fast and easy returns/exchanges.', 'Frequent new arrivals.', 'Unique and eye-catching designs.', 'Eco-friendly clothing options.', 'Cutting-edge technology.', 'Durable and reliable products.', 'Wide product selection.', 'Responsive customer service.', 'Quick and easy setup.', 'Competitive pricing.', 'User-friendly interfaces.', 'Great warranty and support.', 'Fast shipping and delivery.', 'Regular software updates.', 'Thorough cleaning services.', 'Efficient and punctual staff.', 'Use of eco-friendly cleaning products.', 'Attention to detail in cleaning.', 'Flexible scheduling options.', 'Professional and courteous cleaners.', 'Competitive pricing.', 'Excellent odor removal.', 'High-quality equipment and tools.', 'Consistent and reliable cleaning']

agnews = ['words related to country and place.', 'political stunts taken by governments.', 'global issues.', 'words related to war, conflict.', 'economic developments and indicators.', 'technology advancements and innovations.', 'climate change and environmental issues.', 'healthcare and medical breakthroughs.', 'social justice movements and protests.', 'terrorism and security threats.', 'natural disasters and emergencies.', 'trade agreements and international relations.', 'space exploration and discoveries.', 'cultural festivals and events.', 'immigration and refugee crises.', 'human rights violations and advocacy.', 'education reforms and challenges.', 'energy policies and developments.', 'entertainment industry news and trends.', 'sports events and achievements.', 'business mergers and acquisitions.', 'food security and agriculture issues.', 'elections and political campaigns.', 'innovations in renewable energy.', 'cybersecurity threats and breaches.', 'space exploration missions.', 'gender equality initiatives.', 'transportation infrastructure projects.', 'cultural heritage preservation efforts.', 'public health crises and pandemics.', 'international aid and humanitarian efforts.', 'cyberattacks and data privacy concerns.', 'scientific discoveries and breakthroughs.', 'global economic recessions.', 'education access and quality issues.', 'space policy and international cooperation.', 'social media trends and controversies.', 'international diplomacy and summits.', 'art and cultural exhibitions.', 'wildlife conservation efforts.', 'public transportation developments.', 'mental health awareness campaigns.', 'water scarcity and conservation.', 'crime rates and law enforcement efforts.', 'scientific research funding and priorities.', 'immigration policies and debates.', 'climate action initiatives and protests.', 'global tourism trends and challenges.', 'public infrastructure investments.', 'space exploration partnerships.', 'disaster relief and recovery efforts.', 'environmental conservation projects.', 'social media censorship and regulation.', 'international trade disputes and negotiations.', 'name of sports stars.', 'words related to game, competition.', 'ball games like baseball, basketball.', 'name of sport teams.', 'sports events and tournaments.', 'athlete interviews and profiles.', 'team rankings and standings.', 'game scores and statistics.', 'injuries and player health updates.', 'coach decisions and strategies.', 'record-breaking performances.', 'fan reactions and opinions.', 'trades and transfers of players.', 'suspensions and fines in sports.', 'athlete endorsements and sponsorships.', 'Olympic and Paralympic Games coverage.', 'retirement announcements by athletes.', 'sportsmanship and fair play incidents.', 'team rivalries and historic matchups.', 'sports-related scandals and controversies.', 'awards and recognitions in sports.', 'new sports equipment and technology.', 'sports venues and stadium developments.', "athletes' personal lives and off-field activities.", 'team ownership changes and news.', 'sports governing bodies and rule changes.', 'community engagement and charity work by athletes.', 'paralympic sports and achievements.', 'emerging sports and niche competitions.', 'sports documentaries and films.', 'sports betting and gambling trends.', 'sports fashion and merchandise releases.', "athletes' training routines and diets.", 'fan attendance and crowd behavior.', 'team ownership controversies.', 'sports analytics and data-driven insights.', "athletes' philanthropic efforts.", 'gender equality and diversity in sports.', 'sports-related books and literature.', 'sports science and performance enhancements.', 'sports psychology and mental toughness.', 'athlete retirements and comebacks.', 'eSports and online gaming competitions.', 'athlete suspensions and bans.', 'sports memorabilia auctions.', 'athlete social media activity.', 'sports-related art and exhibitions.', 'sports traditions and rituals.', 'sports charity events and fundraisers.', "athletes' community involvement.", "sports fan clubs and supporters' groups.", 'sports science breakthroughs.', 'athlete comebacks after injury.', 'sports betting regulations and legislation.', 'words related to currency, money.', 'the numerical amount of dollars.', 'the symbol like $.', 'words related to stock, Portfolio.', 'economic indicators and reports.', 'stock market indices and performance.', 'company earnings and financial results.', 'investment strategies and advice.', 'interest rates and central bank policies.', 'commodity prices and market trends.', 'cryptocurrency news and developments.', 'mergers and acquisitions in the business world.', 'startup funding and venture capital investments.', 'international trade agreements and tariffs.', 'consumer spending and retail trends.', 'taxation policies and reforms.', 'business regulations and government policies.', 'energy prices and renewable energy updates.', 'market volatility and risk assessment.', 'real estate market reports and trends.', 'foreign exchange rates and currency fluctuations.', 'business bankruptcies and closures.', 'entrepreneurial success stories.', 'initial public offerings (IPOs).', 'business ethics and corporate responsibility.', 'trade wars and global economic tensions.', 'economic stimulus packages and government spending.', 'consumer confidence indices.', 'investment portfolio diversification.', 'business leadership changes and CEO appointments.', 'financial fraud and white-collar crime.', 'hedge funds and investment strategies.', 'venture capital funding rounds.', 'credit ratings and credit market news.', 'income inequality and wealth distribution.', 'economic forecasts and predictions.', 'banking industry developments.', 'foreign direct investment (FDI).', 'economic recessions and recoveries.', 'business sustainability initiatives.', 'entrepreneurship and small business news.', 'consumer debt levels and trends.', 'financial literacy and education programs.', 'trade agreements and negotiations.', 'private equity investments and deals.', 'business technology and innovation.', 'credit card and payment industry updates.', 'labor market statistics and employment trends.', 'business conferences and industry events.', 'economic sanctions and trade restrictions.', 'retirement savings and pension fund news.', 'stock market analysis and expert opinions.', 'consumer price index (CPI) reports.', 'business insolvencies and liquidations.', 'name of scientists or the word scientists.', 'words related to technical devices.', 'words related to universe, space, planet.', 'words related to the natural landscape.', 'scientific discoveries and breakthroughs.', 'research studies and findings.', 'technology innovations and advancements.', 'space exploration missions and updates.', 'environmental conservation efforts.', 'climate change research and reports.', 'medical treatments and pharmaceutical developments.', 'artificial intelligence (AI) and machine learning.', 'robotics and automation in various industries.', 'quantum computing and quantum technologies.', 'biotechnology and genetic engineering.', 'cybersecurity threats and data breaches.', 'nanotechnology applications and research.', 'clean energy technologies and renewables.', 'virtual reality (VR) and augmented reality (AR).', 'scientific missions to other planets.', 'STEM education initiatives and programs.', 'telecommunications and 5G technology.', 'genomic sequencing and personalized medicine.', 'science policy and government funding.', 'wildlife conservation efforts and biodiversity news.', 'climate action initiatives and protests.', 'biomedical research and breakthroughs.', 'space telescopes and astronomical discoveries.', 'startups and tech industry news.', 'space agencies and their missions.', 'green technology and sustainable practices.', '3D printing and additive manufacturing.', 'science ethics and responsible research.', 'neuroscience and brain-related studies.', 'tech giants and major industry players.', 'astronomy and astrophysics news.', 'science communication and popular science.', 'internet of things (IoT) developments.', 'biomedical ethics and gene editing debates.', 'science and technology in education.', 'space policy and international cooperation.', 'climate-related disasters and mitigation efforts.', 'scientific awards and recognitions.', 'emerging technologies and startups.', 'consumer electronics and gadgets.', 'citizen science projects and participation.', 'science exhibitions and museums.', 'ethical debates in AI and technology.', 'genomic privacy and data security.', 'marine biology and oceanography research.', 'space tourism and commercial spaceflight.', 'science and tech-related podcasts.', 'STEM diversity and inclusion efforts.', 'science and tech-related art and culture']

dbpedia = ['the name of the company.', 'the location of the company', 'the founding year of the company', 'words related to organization, group.', 'the mission statement of the company', 'the vision statement of the company', 'the core values of the company', 'the industry or sector the company operates in', 'the products or services offered by the company', 'the target market or customer demographics', 'the size of the company in terms of employees', "the company's unique selling proposition (USP)", "the company's market share or position in the industry", "the company's competitive advantages", "the company's key executives or leadership team", "the company's corporate culture", "the company's commitment to sustainability and CSR", "the company's history of awards and achievements", "the company's global presence or international reach", "the company's partnerships and collaborations", "the company's technological innovations", "the company's research and development efforts", "the company's financial stability and performance", "the company's growth trajectory and future goals", "the company's commitment to diversity and inclusion", "the company's customer testimonials or case studies", "the company's brand identity and logo", "the company's social media presence and website", "the company's community involvement and philanthropy", "the company's regulatory compliance and certifications", "the company's approach to innovation and creativity", "the company's approach to quality control and assurance", "the company's commitment to employee development and training", "the company's approach to customer support and service", 'the name of the school.', 'the location of the school', 'the founding year of the school', 'words related to college, university.', 'Academic programs offered', 'Accreditation status', 'Mission and vision statements', 'Core values', 'Faculty and staff profiles', 'Student demographics', 'Enrollment statistics', 'Tuition fees and financial aid', 'Admission requirements', 'Campus facilities', 'Library resources', 'Research centers and labs', 'Extracurricular activities', 'Student organizations', 'Alumni network', 'International student support', 'Online learning options', 'Community outreach programs', 'Career services', 'Internship opportunities', 'Student testimonials', 'Notable alumni', 'Publications and journals', 'Student housing options', 'Diversity and inclusion initiatives', 'Health and wellness services', 'Sustainability efforts', 'Transportation and parking', 'Technology infrastructure', 'Events and academic calendar', "the artist's name.", "the artist's works", "the artist's born date", 'words related to music, painting.', "The artist's background.", "The artist's signature style.", "The artist's inspirations.", "The artist's creative process.", "The artist's notable achievements.", "The artist's preferred mediums.", "The artist's early influences.", "The artist's cultural impact.", "The artist's innovative techniques.", "The artist's critical reception.", "The artist's famous collaborations.", "The artist's awards and honors.", "The artist's thematic interests.", "The artist's iconic works.", "The artist's use of color.", "The artist's use of light and shadow.", "The artist's evolution over time.", "The artist's influence on contemporary art.", "The artist's cultural significance.", "The artist's global reach.", "The artist's impact on their genre.", "The artist's role in art movements.", "The artist's personal anecdotes.", "The artist's connection to their hometown.", "The artist's role in promoting social causes.", "The artist's memorable exhibitions.", "The artist's contributions to art history.", "The artist's unique artistic voice.", "The artist's collectors and patrons.", "The artist's enduring legacy.", "the athlete's or sports stars' name.", 'the sport the athlete plays (e.g. football, basketball).', "the athlete's or sports stars' born date", 'words related to ball games, competition.', "The athlete's or sports star's nationality.", "The athlete's or sports star's position or role in the sport.", "The athlete's or sports star's height and weight.", "The athlete's or sports star's team or club.", "The athlete's or sports star's jersey number.", "The athlete's or sports star's career achievements.", "The athlete's or sports star's signature moves or techniques.", "The athlete's or sports star's records and statistics.", "The athlete's or sports star's career milestones.", "The athlete's or sports star's current and past endorsements.", "The athlete's or sports star's playing style.", "The athlete's or sports star's training regimen.", "The athlete's or sports star's early life and upbringing.", "The athlete's or sports star's college or youth achievements.", "The athlete's or sports star's mentors or coaches.", "The athlete's or sports star's family background.", "The athlete's or sports star's hobbies and interests outside of sports.", "The athlete's or sports star's philanthropic efforts or charities.", "The athlete's or sports star's dietary preferences or nutrition regimen.", "The athlete's or sports star's preferred gear or equipment.", "The athlete's or sports star's career setbacks or injuries.", "The athlete's or sports star's on-field or on-court demeanor.", "The athlete's or sports star's fan following and social media presence.", "The athlete's or sports star's rivalries and memorable matchups.", "The athlete's or sports star's awards and accolades.", "The athlete's or sports star's retirement plans or future goals.", "The athlete's or sports star's impact on the sport and society.", "The athlete's or sports star's inspirational quotes or philosophies.", "The athlete's or sports star's endorsement deals and sponsorships.", "The athlete's or sports star's fan clubs or support groups.", "the office holder's name.", "the office holder's position.", "the office holder's born date", 'words related to politician, businessman.', "The office holder's education background.", "The office holder's political party affiliation.", "The office holder's previous political experience.", "The office holder's notable achievements.", "The office holder's hometown or place of origin.", "The office holder's family background.", "The office holder's campaign promises.", "The office holder's campaign slogans.", "The office holder's campaign platform.", "The office holder's stance on key issues.", "The office holder's political ideology.", "The office holder's religious beliefs, if relevant.", "The office holder's stance on economic policies.", "The office holder's stance on healthcare policies.", "The office holder's stance on environmental issues.", "The office holder's stance on immigration policies.", "The office holder's stance on foreign relations.", "The office holder's previous occupations or careers.", "The office holder's campaign fundraising efforts.", "The office holder's campaign endorsements.", "The office holder's primary campaign opponents.", "The office holder's campaign fundraising sources.", "The office holder's stance on social issues.", "The office holder's legislative track record.", "The office holder's voting record on key bills.", "The office holder's public speaking style.", "The office holder's charisma and personality traits.", "The office holder's approach to public engagement.", "The office holder's notable endorsements or supporters.", "The office holder's plans for the future while in office.", 'the model type of the transportation or vehicle.', 'the production date of the transportation or vehicle.', 'the functions of the transportation or vehicle.', 'words related to ship, car, train.', 'the manufacturer of the transportation or vehicle.', "the vehicle's fuel type.", 'the maximum speed of the transportation.', 'the passenger capacity of the vehicle.', "the vehicle's fuel efficiency rating.", 'the engine type and specifications.', "the vehicle's weight and dimensions.", "the vehicle's safety features.", 'the environmental impact of the transportation.', "the vehicle's pricing and affordability.", "the transportation's availability in different colors.", "the vehicle's warranty and maintenance options.", "the transportation's cargo capacity.", "the vehicle's entertainment and technology features.", "the transportation's off-road capabilities.", "the vehicle's towing capacity.", "the transportation's fuel tank capacity.", "the vehicle's interior and exterior design.", "the transportation's handling and maneuverability.", "the vehicle's transmission type.", "the transportation's powertrain options.", "the vehicle's suspension system.", "the transportation's braking system.", "the vehicle's infotainment system.", "the transportation's accessibility features.", "the vehicle's resale value.", "the transportation's history and reviews.", "the vehicle's maintenance schedule.", "the transportation's energy efficiency.", "the vehicle's unique or standout features.", 'the name of the building.', 'the built date of the building.', 'the location of the building.', 'words related to the type of the building (e.g. church, historic house, park, resort).', 'The architect/designer of the building.', 'The architectural style of the building (e.g., Gothic, Modern, Colonial).', 'The purpose or function of the building (e.g., residential, commercial, cultural).', 'The historical significance of the building.', "The unique or distinctive features of the building's design.", 'The materials used in the construction of the building.', 'The height or number of stories in the building.', 'The interior layout or floor plan of the building.', 'The landscaping or outdoor spaces surrounding the building.', "The building's structural elements (e.g., columns, beams, arches).", "The building's role in the local community or cityscape.", 'The architectural innovations or advancements used in the building.', "The building's accessibility features (e.g., ramps, elevators).", "The building's environmental sustainability features (e.g., LEED certification).", "The building's original purpose and any subsequent renovations or adaptations.", 'The cultural or artistic significance of the building.', "The building's influence on the surrounding area or other architecture.", "The building's connection to famous individuals or events.", "The building's role in local or national history.", "The building's current use or tenants.", "The building's exterior features (e.g., facades, windows, roof).", "The building's interior decor or artwork.", "The building's technological features or advancements.", "The building's relationship to its natural surroundings (e.g., waterfront location).", "The building's inclusion in any preservation or heritage programs.", "The building's popularity as a tourist attraction.", "The building's connection to local folklore or legends.", "The building's association with a specific era or period in history.", "The building's awards or recognitions for design or preservation.", "The building's symbolism or cultural representation.", 'the name of the natural place.', 'the length or height of the natural place.', 'the location of the natural place.', 'words related to mountain, river.', 'The unique geological formation of the area.', 'The surrounding ecosystem and biodiversity.', 'The historical significance of the place.', 'The cultural importance to local communities.', 'The primary flora and fauna species.', 'The climate and weather patterns.', 'The accessibility and transportation options.', 'The recreational activities available.', 'The local cuisine and food specialties.', 'The flora and fauna conservation efforts.', 'The presence of hiking trails or pathways.', 'The geological features like caves, canyons, or waterfalls.', 'The water sources such as lakes, ponds, or springs.', 'The nearby camping or accommodation options.', 'The viewpoints or scenic overlooks.', 'The natural sounds and wildlife noises.', 'The safety and emergency information.', 'The best times to visit, considering seasons.', "The local flora's colors during different seasons.", 'The presence of endangered species.', 'The geological history and formation process.', 'The opportunities for birdwatching.', 'The presence of indigenous plants.', 'The sustainability practices in place.', "The geological features' age and formation details.", 'The potential for stargazing and astronomy.', 'The impact of climate change on the area.', 'The local traditions and folklore related to the place.', 'The availability of guided tours or interpretive programs.', 'The potential for scientific research in the area.', 'the name of the village.', 'the population of the village.', 'the census of the village.', 'words related to district, families.', 'The geographical location of the village.', 'The history and origin of the village.', 'The climate and weather conditions in the village.', 'The main agricultural crops grown in the village.', 'The prominent landmarks and monuments in the village.', 'The cultural festivals celebrated in the village.', 'The primary language spoken by the villagers.', 'The local cuisine and traditional dishes.', 'The education facilities and schools in the village.', 'The healthcare services available in the village.', 'The transportation options and connectivity.', 'The religious diversity and places of worship.', 'The natural resources found in the village.', "The flora and fauna in the village's surroundings.", 'The traditional crafts and artisanal skills.', 'The local economy and sources of livelihood.', 'The governance structure and village council.', 'The local customs and traditions.', 'The historical events that shaped the village.', 'The water sources and sanitation facilities.', 'The recreational activities and sports played.', 'The traditional attire and clothing styles.', 'The demographics of the village population.', 'The wildlife or nature reserves nearby.', 'The major challenges or issues faced by the village.', 'The local flora and unique plant species.', 'The folklore and legends associated with the village.', 'The local markets and trade practices.', "The village's role in the region's history or culture.", 'The traditional music and dance forms.', 'the species of the animal.', 'the habitat of the animal.', 'the type of the animal (e.g. bird, insect, moth).', 'words related to genus, family.', 'The physical characteristics of the animal.', 'The diet and feeding habits of the animal.', 'The geographic distribution of the species.', 'The unique adaptations or evolutionary traits of the animal.', 'The size and weight range of the animal.', 'The behavior and social structure of the animal.', 'The life cycle and reproduction of the species.', 'The conservation status and threats to the animal.', 'The role of the animal in its ecosystem.', 'The classification and taxonomy of the species.', 'The predators and prey of the animal.', 'The lifespan and longevity of the species.', 'The locomotion and movement patterns of the animal.', 'The sensory organs and perception of the species.', 'The vocalizations or communication methods used by the animal.', 'The historical or cultural significance of the species.', 'The reproductive strategies and mating rituals of the animal.', 'The migratory patterns and seasonal movements of the species.', 'The role of the animal in human society or folklore.', 'The genetic diversity and subspecies of the species.', 'The interaction with other species in its habitat.', 'The conservation efforts and initiatives for the animal.', 'The economic importance of the species (e.g., as a food source).', 'The role of the animal in scientific research or studies.', 'The historical or fossil records of the species.', 'The cultural symbolism or mythology associated with the animal.', 'The impact of climate change or habitat loss on the species.', 'The medical or ecological relevance of the species.', 'The population trends and demographics of the species.', 'The unique or intriguing facts about the animal.', 'the name of the plant.', 'the genus or family of plant.', 'the place where the plant was found.', 'words related to grass, herb, flower.', 'The botanical classification of the plant.', 'The native habitat of the plant.', 'The ecological role of the plant in its ecosystem.', 'The growth habit (e.g., tree, shrub, vine, herb).', "The plant's size at maturity.", 'The unique physical characteristics of leaves.', 'The shape and color of flowers.', 'The season when the plant typically blooms.', 'The scent or fragrance of the flowers.', 'The type of fruit produced (if applicable).', "The plant's method of reproduction (e.g., seeds, spores, cuttings).", 'The preferred soil type and pH for optimal growth.', 'The ideal light conditions for the plant.', "The plant's drought tolerance and water requirements.", 'The common pests and diseases that affect the plant.', 'The historical or cultural significance of the plant.', 'The ethnobotanical uses of the plant by indigenous peoples.', "The plant's role in traditional medicine.", "The plant's contribution to biodiversity.", "The impact of climate change on the plant's distribution.", 'The conservation status of the plant (e.g., endangered, vulnerable).', "The plant's role in landscaping and horticulture.", "The plant's ability to attract pollinators (e.g., bees, butterflies).", 'The importance of the plant in local ecosystems.', "The plant's historical or cultural symbolism.", "The plant's role in culinary traditions (if edible).", 'The methods of cultivation and care for the plant.', "The plant's response to pruning and shaping.", "The plant's seasonal changes in appearance.", 'The current conservation efforts aimed at protecting the plant.', 'the name of the album.', 'the type of music, instrument.', 'the release date of the album.', 'words related to band, studio.', 'the album cover artwork.', "the artist or band's name.", 'the tracklist of songs.', 'the record label or production company.', 'the genre or musical style.', 'collaborating artists or guest musicians.', "the producer's name.", 'liner notes or credits.', "the album's total runtime.", 'awards or accolades received.', 'critical reviews or quotes.', "the album's concept or theme.", 'the lead single or hit song.', 'lyric excerpts or notable phrases.', 'musical influences or inspirations.', 'live performance or tour information.', 'recording location or studio details.', 'album sales or chart performance.', 'awards won or nominations.', 'album format (e.g., vinyl, CD, digital).', 'dedications or acknowledgments.', 'album production history or anecdotes.', 'collaboration stories or anecdotes.', "album's impact on the music industry.", 'bonus tracks or deluxe edition details.', 'behind-the-scenes photos or videos.', 'album release parties or events.', "the album's promotional campaign.", "special editions or collector's items.", 'upcoming projects or future releases.', 'the name of the film.', 'the maker or producer of the film.', 'the type of the film (e.g. drama, science fiction, comedy, cartoon, animation).', 'words related to TV, video.', 'The release date of the film.', "The film's tagline or catchphrase.", 'The main actors and actresses in the film.', 'A brief plot summary or synopsis.', "The film's director and/or screenwriter.", "The film's rating (e.g., PG-13, R, G).", "The film's runtime or duration.", "The film's production company or studio.", "The film's cinematographer or director of photography.", "The film's composer or music director.", 'Notable awards or nominations received by the film.', "The film's setting or location.", "The film's target audience or demographic.", "The film's source material (e.g., based on a novel, true story).", "The film's visual effects or CGI (Computer-Generated Imagery).", 'Key themes or motifs explored in the film.', "The film's costume designer or wardrobe department.", "The film's special features (e.g., 3D, IMAX).", 'Notable quotes or dialogues from the film.', "The film's critical reception or reviews.", "The film's box office performance or earnings.", "The film's teaser or trailer.", "The film's poster or promotional artwork.", 'Behind-the-scenes footage or making-of documentaries.', "The film's historical or cultural significance.", "The film's franchise or sequels, if applicable.", "The film's distributor or international release details.", "The film's age-appropriateness or parental guidance notes.", 'Notable guest appearances or cameos in the film.', "The film's impact on popular culture or references in other media.", 'the name of the written work.', 'the author of the film.', 'the type of the written work (e.g. novel, manga, journal).', 'words related to book.', 'the publication date of the work.', 'the genre or literary category of the work (e.g., science fiction, romance).', 'the main themes or motifs explored in the work.', 'the setting or time period in which the story takes place.', 'the main characters in the story.', 'the synopsis or summary of the plot.', 'the target audience or age group for the work.', 'the major conflict or central problem in the story.', 'the tone or mood of the work (e.g., dark, humorous).', 'the narrative point of view (e.g., first-person, third-person).', 'the length or word count of the written work.', 'the original language in which the work was written.', 'the cultural or historical context of the work.', 'the significance or impact of the work in literature.', 'the awards or recognitions received by the work.', 'the dedication or acknowledgments in the book.', 'the table of contents for non-fiction works.', 'the foreword or introduction by another author or expert.', "the preface or author's note explaining the purpose of the work.", 'the cover art or design of the book.', 'the page count or chapter count in the work.', 'the ISBN (International Standard Book Number) of the book.', 'the publisher and imprint of the work.', 'the availability of the work in different formats (e.g., hardcover, ebook).', 'the endorsements or reviews from other authors or critics.', 'the dedication or tribute to someone or something special.', 'the quotations or epigraphs used at the beginning of chapters.', 'the footnotes or endnotes in non-fiction or scholarly works.', 'the acknowledgments section for contributors or supporters.', 'the copyright information and legal notices']


# med_abs = ['Unexplained weight loss.',
#  "Persistent fatigue that doesn't improve with rest.",
#  'Unexplained fever, especially at night.',
#  "Persistent cough that doesn't go away.",
#  'Hoarseness or voice changes lasting more than a few weeks.',
#  'Difficulty swallowing or feeling of food getting stuck.',
#  'Persistent indigestion or heartburn.',
#  'Changes in a mole, such as asymmetry, border irregularity, color variation, diameter >6mm, or evolution (ABCDEs).',
#  'A sore that does not heal.',
#  'Unusual bleeding or discharge from any body opening (e.g., vaginal, rectal, nipple, urinary).',
#  'Persistent pain in a specific area (e.g., back, abdomen, bone).',
#  'Swollen lymph nodes in the neck, armpit, or groin.',
#  'Unexplained anemia.',
#  'Easy bruising or bleeding without injury.',
#  'Persistent headaches, especially if new or worsening.',
#  'New onset seizures.',
#  'Changes in vision or hearing.',
#  'Numbness or weakness in any part of the body.',
#  'Bone pain that is persistent or worsens at night.',
#  "Swelling in an arm or leg that doesn't go away.",
#  'Persistent sore throat or difficulty opening mouth.',
#  'Blood in the urine.',
#  'Blood in the stool (either bright red or black/tarry).',
#  'Nipple discharge or changes in nipple appearance.',
#  'Skin changes such as yellowing (jaundice), darkening, redness, or unexplained itching.',
#  'Loss of appetite or feeling full quickly.',
#  'Recurrent infections.',
#  'Unexplained muscle weakness.',
#  'Persistent abdominal pain or discomfort.',
#  'Persistent nausea or vomiting.',
#  'Diarrhea.',
#  'Constipation.',
#  'Blood in stool (hematochezia or melena).',
#  'Mucus in stool.',
#  'Changes in stool color (e.g., pale, black, tarry).',
#  'Unexplained weight loss.',
#  'Loss of appetite (anorexia).',
#  'Difficulty swallowing (dysphagia).',
#  'Painful swallowing (odynophagia).',
#  'Feeling of fullness after eating small amounts (early satiety).',
#  'Jaundice (yellowing of skin or eyes).',
#  'Dark urine.',
#  'Pale stools (acholic stools).',
#  'Rectal bleeding.',
#  'Abdominal distension.',
#  'Excessive belching or burping.',
#  'Fever.',
#  'Chills.',
#  'Fatigue.',
#  'Itching (pruritus), especially with liver conditions.',
#  'Bad breath (halitosis).',
#  'Regurgitation of food or sour liquid.',
#  'Sensation of a lump in the throat (globus sensation).',
#  'Abdominal tenderness on palpation.',
#  'Changes in bowel habits (e.g., alternating diarrhea and constipation).',
#  'Unexplained anemia.',
#  'Muscle weakness or wasting.',
#  'Fluid retention (ascites or peripheral edema).',
#  'Pain that worsens after eating.',
#  'Pain that improves after eating.',
#  'Difficulty with balance or coordination.',
#  'Dizziness or vertigo.',
#  'Slurred speech or difficulty speaking (dysarthria).',
#  'Memory loss or confusion.',
#  'Difficulty swallowing (dysphagia).',
#  'Seizures or convulsions.',
#  'Tremors or involuntary shaking.',
#  'Muscle stiffness or rigidity.',
#  'Changes in personality or behavior.',
#  'Difficulty concentrating or paying attention.',
#  'Loss of smell or taste.',
#  'Bladder or bowel control problems.',
#  'Unexplained fatigue or excessive sleepiness.',
#  'Difficulty walking or changes in gait.',
#  'Muscle spasms or cramps.',
#  'Drooping of one side of the face.',
#  'Nystagmus (involuntary eye movements).',
#  'Sensitivity to light (photophobia).',
#  'Difficulty with fine motor skills (e.g., writing, buttoning).',
#  'Changes in reflexes (absent or exaggerated).',
#  'Burning or electric shock-like pain (neuropathic pain).',
#  'Difficulty understanding language (receptive aphasia).',
#  'Inability to recognize familiar objects or faces (agnosia).',
#  'Difficulty planning or organizing tasks.',
#  'Persistent ringing in the ears (tinnitus).',
#  'Changes in sleep patterns (insomnia, hypersomnia).',
#  'Sudden, unexplained falls.',
#  'Muscle wasting or atrophy.',
#  'Difficulty regulating body temperature.',
#  'Loss of proprioception (sense of body position).',
#  'Chest pain or discomfort.',
#  'Fatigue or weakness.',
#  'Swelling in the ankles, feet, or legs.',
#  'Dizziness or lightheadedness.',
#  'Fainting or syncope.',
#  'Palpitations or a sensation of a racing heart.',
#  'Cough, especially with pink, frothy sputum.',
#  'Waking up at night feeling breathless (paroxysmal nocturnal dyspnea).',
#  'Difficulty breathing when lying flat (orthopnea).',
#  'Coldness or numbness in the extremities.',
#  'Skin discoloration (e.g., bluish or pale) in the extremities.',
#  'Non-healing sores or ulcers on the legs or feet.',
#  'Hair loss on the legs.',
#  'Thickened or brittle toenails.',
#  'Erectile dysfunction.',
#  'Nausea or loss of appetite.',
#  'Abdominal swelling or tenderness.',
#  'Sudden weight gain.',
#  'High blood pressure readings.',
#  'Low blood pressure readings (hypotension).',
#  'Irregular pulse.',
#  'Weak or absent pulses in the extremities.',
#  'Crackles or rales heard in the lungs.',
#  'Enlarged liver (hepatomegaly).',
#  'Cool, clammy skin.',
#  'Confusion or disorientation.',
#  'Headaches (especially severe or sudden onset).',
#  'Temporary loss of vision or speech.',
#  'Pain in the arm, shoulder, neck, jaw, or back.',
#  'Excessive sweating.',
#  'Generalized weakness.',
#  'Profound fatigue or malaise.',
#  'Loss of appetite (anorexia).',
#  'Nausea.',
#  'Vomiting.',
#  'Diarrhea.',
#  'Constipation.',
#  'Abdominal pain or discomfort.',
#  'Headache.',
#  'Dizziness or lightheadedness.',
#  'Shortness of breath (dyspnea).',
#  'Persistent cough.',
#  'Chest pain or pressure.',
#  'Localized or generalized swelling (edema).',
#  'Yellowing of skin or eyes (jaundice).',
#  'Pale skin (pallor).',
#  'Skin rash or lesions.',
#  'Muscle aches (myalgia).',
#  'Joint pain or stiffness (arthralgia).',
#  'Swollen lymph nodes (lymphadenopathy).',
#  'Unexplained weight loss.',
#  'Unexplained weight gain.',
#  'Altered mental status or confusion.',
#  'Difficulty sleeping (insomnia).',
#  'Excessive sleepiness (hypersomnia).',
#  'Frequent urination (polyuria).',
#  'Painful urination (dysuria).',
#  'Reduced urine output (oliguria).',
#  'Night sweats.',
#  'Chills or rigors.']

med_abs = [
    "aabbbcc1", "aabbbcc2", "aabbbcc3", "aabbbcc4", "aabbbcc5",
    "aabbbcc6", "aabbbcc7", "aabbbcc8", "aabbbcc9", "aabbbcc10",
    "aabbbcc11", "aabbbcc12", "aabbbcc13", "aabbbcc14", "aabbbcc15",
    "aabbbcc16", "aabbbcc17", "aabbbcc18", "aabbbcc19", "aabbbcc20",
    "aabbbcc21", "aabbbcc22", "aabbbcc23", "aabbbcc24", "aabbbcc25",
    "aabbbcc26", "aabbbcc27", "aabbbcc28", "aabbbcc29", "aabbbcc30",
    "aabbbcc31", "aabbbcc32", "aabbbcc33", "aabbbcc34", "aabbbcc35",
    "aabbbcc36", "aabbbcc37", "aabbbcc38", "aabbbcc39", "aabbbcc40",
    "aabbbcc41", "aabbbcc42", "aabbbcc43", "aabbbcc44", "aabbbcc45",
    "aabbbcc46", "aabbbcc47", "aabbbcc48", "aabbbcc49", "aabbbcc50",
    "aabbbcc51", "aabbbcc52", "aabbbcc53", "aabbbcc54", "aabbbcc55",
    "aabbbcc56", "aabbbcc57", "aabbbcc58", "aabbbcc59", "aabbbcc60",
    "aabbbcc61", "aabbbcc62", "aabbbcc63", "aabbbcc64", "aabbbcc65",
    "aabbbcc66", "aabbbcc67", "aabbbcc68", "aabbbcc69", "aabbbcc70",
    "aabbbcc71", "aabbbcc72", "aabbbcc73", "aabbbcc74", "aabbbcc75",
    "aabbbcc76", "aabbbcc77", "aabbbcc78", "aabbbcc79", "aabbbcc80",
    "aabbbcc81", "aabbbcc82", "aabbbcc83", "aabbbcc84", "aabbbcc85",
    "aabbbcc86", "aabbbcc87", "aabbbcc88", "aabbbcc89", "aabbbcc90",
    "aabbbcc91", "aabbbcc92", "aabbbcc93", "aabbbcc94", "aabbbcc95",
    "aabbbcc96", "aabbbcc97", "aabbbcc98", "aabbbcc99", "aabbbcc100",
    "aabbbcc101", "aabbbcc102", "aabbbcc103", "aabbbcc104", "aabbbcc105",
    "aabbbcc106", "aabbbcc107", "aabbbcc108", "aabbbcc109", "aabbbcc110",
    "aabbbcc111", "aabbbcc112", "aabbbcc113", "aabbbcc114", "aabbbcc115",
    "aabbbcc116", "aabbbcc117", "aabbbcc118", "aabbbcc119", "aabbbcc120",
    "aabbbcc121", "aabbbcc122", "aabbbcc123", "aabbbcc124", "aabbbcc125",
    "aabbbcc126", "aabbbcc127", "aabbbcc128", "aabbbcc129", "aabbbcc130",
    "aabbbcc131", "aabbbcc132", "aabbbcc133", "aabbbcc134", "aabbbcc135",
    "aabbbcc136", "aabbbcc137", "aabbbcc138", "aabbbcc139", "aabbbcc140",
    "aabbbcc141", "aabbbcc142", "aabbbcc143", "aabbbcc144", "aabbbcc145",
    "aabbbcc146", "aabbbcc147", "aabbbcc148", "aabbbcc149", "aabbbcc150"
]


legal = ["Appellate court's agreement with the lower court's interpretation and application of legal principles.",
 "Appellate court finding that the lower court's factual findings were supported by substantial evidence.",
 'The original judgment becoming final and enforceable without alteration.',
 'Case remanded to the lower court for the execution of the original judgment.',
 "Absence of any reversal, modification, or vacatur of the lower court's decision.",
 "The appellate court's opinion providing detailed reasoning for upholding the lower court's decision.",
 "The appellant's arguments being rejected by the higher court.",
 'Direct reference and analysis of the controlling precedent.',
 'Court finds no compelling reason to distinguish the current facts from the precedent.',
 'The scope of the prior decision is determined to cover the present legal issue.',
 "The court's decision aligns with the underlying policy objectives of the precedent.",
 'Application of a specific multi-factor test or standard articulated in the earlier case.',
 'Adoption of a specific legal definition from a prior case.',
 'Affirmation of a specific holding on a particular legal issue.',
 'Reliance on a prior case as controlling precedent for a specific point.',
 'Application of a previously established rule to the facts of the current case.',
 "Integration of a prior case's analytical framework or methodology.",
 'Declaration that a specific aspect of a prior ruling continues to be valid law.',
 "Upholding a specific part of a lower court's judgment based on prior reasoning.",
 'Reinforcement of a foundational legal principle articulated in an earlier decision.',
 'Citing a prior case as highly persuasive authority for a particular argument.',
 "Direct quotation from the prior case's opinion.",
 'Summary of the holding or rule derived from the cited case.',
 "Explanation of how the prior case's reasoning applies to the current facts.",
 'Use of citation signals such as "See," "See also," "Cf.," or "But see" preceding the citation.',
 'Pinpoint citation to a specific page or paragraph within the prior opinion.',
 'Discussion of the factual similarities or differences between the current case and the cited precedent.',
 'Explicit statement that the court is "following," "distinguishing," or "overruling" the prior authority.',
 'Attribution of a legal principle, test, or doctrine to a specific foundational case.',
 'Reference to the specific court that issued the prior decision (e.g., "As the Supreme Court held in...").',
 'Analysis of the precedential weight or binding nature of the cited authority.',
 'Direct application of a rule or principle established in a prior case to the facts at hand.',
 'Detailed explanation of why a prior case is factually or legally distinguishable from the current matter.',
 'Synthesis of principles from multiple prior cases to form a comprehensive legal rule or framework.',
 'Interpretation or clarification of the meaning, scope, or applicability of a prior holding.',
 "Citation of the prior case as authoritative support for a legal proposition in the court's reasoning.",
 'Direct response to arguments made by parties that rely on specific precedents.',
 'Discussion of the underlying policy rationale or implications that informed a prior decision.',
 'Decision to overrule, modify, or limit the precedential value of a prior case.',
 'Identification of the specific limitations or narrow scope within which a prior ruling applies.',
 'Identification of the specific legal rule or binding holding (ratio decidendi) derived from the prior case.',
 "Explicit statement of the court's action regarding the precedent (e.g., affirming, distinguishing, overruling, or extending its application).",
 'Examination of the underlying policy objectives or societal impacts considered by the prior court or relevant to the current application of the precedent.',
 'Synthesis of multiple prior decisions to articulate a comprehensive legal doctrine or framework.',
 "Assessment of the prior decision's continued relevance or adaptability in light of changed circumstances or subsequent legal developments.",
 'Identification of a different legal issue or question presented in the current case.',
 "Narrowing the scope or interpretation of the prior case's holding.",
 'Discussion of the underlying purpose or policy of the prior rule not being served by its application to the current facts.',
 'Demonstration that the specific elements or conditions required by the prior precedent are not met in the present case.',
 'Reference to different statutory provisions or jurisdictional contexts governing the current dispute.',
 'Pointing out the absence of a critical fact or circumstance that was central to the prior decision.',
 'Articulating why the *ratio decidendi* (reasoning) of the prior case is not applicable to the distinct facts at hand.',
 'Explicit acknowledgment by the court of its obligation to follow the precedent.',
 'The court finds no material factual or legal distinctions to deviate from the prior ruling.',
 'Invocation of the doctrine of *stare decisis* as the basis for the decision.',
 'Direct and primary citation to the controlling case as the sole or primary legal authority.',
 "The court's decision does not introduce new legal principles or modify existing ones.",
 "Detailed comparison of the current case's facts to those of the precedent, highlighting similarities.",
 'Citation of a case for general background or historical context.',
 'Reference to a case as an example of a widely accepted legal principle.',
 'Inclusion of the case in a footnote without substantive discussion in the main text.',
 'Use of introductory phrases like "see generally" or "cf." before the citation.',
 "Absence of detailed factual or legal analysis of the cited case's holding.",
 "No direct application of the prior case's specific reasoning to the immediate facts.",
 'Mention of a case as part of a broader "line of cases" establishing a general rule.',
 'No attempt to distinguish or reconcile the prior case with the current facts or other precedents.',
 'The case is cited as a foundational or seminal authority without further elaboration.',
 'A brief parenthetical explanation accompanying the citation, rather than a full discussion.',
 'The prior case established a specific legal test or multi-factor framework being applied.',
 'Both cases involve the interpretation of the same statute, regulation, or constitutional provision.',
 'The earlier decision serves as binding or highly persuasive precedent for the current court.',
 'The court is evaluating whether to extend, limit, or distinguish the holding of the previous case.',
 'The prior case articulates a foundational legal principle that underpins the current legal analysis.',
 'The factual scenario, though not identical, is sufficiently analogous to warrant comparative analysis.']



ecom = ['Color options are typically a key selection criterion.',
 'Style or design aesthetic (e.g., modern, rustic, minimalist) is often highlighted.',
 'Weight of the product can be relevant for handling or stability.',
 'Care instructions (e.g., machine washable, wipe clean) are usually provided.',
 'Durability or expected lifespan can be a significant selling point.',
 'Warranty information is frequently offered for larger or more complex items.',
 'Capacity or volume (e.g., for storage bins, pitchers, wastebaskets) is often specified.',
 'Power source (e.g., battery-operated, plug-in, manual) for electrical or mechanical items.',
 'Energy efficiency ratings (e.g., Energy Star) for appliances are important.',
 'Safety features (e.g., non-slip base, child-lock, tip-over restraint) are crucial for certain products.',
 'Indoor or outdoor suitability is a common distinction for furniture and decor.',
 'Compatibility with other household items (e.g., mattress size for bed frames, bulb type for lamps) is often noted.',
 'Number of pieces included in a set or package is clearly stated.',
 'Texture or finish (e.g., matte, glossy, soft-touch, woven) is often described for tactile appeal.',
 'Special features like smart home integration, adjustable settings, or foldable design are highlighted.',
 'Room suitability (e.g., kitchen, bathroom, living room, bedroom) guides product placement.',
 'Installation requirements (e.g., wall-mounted, freestanding, requires plumbing) are detailed.',
 'Specific cleaning method (e.g., dishwasher safe, hand wash only, spot clean) is provided.',
 'Heat resistance for kitchenware, oven mitts, or protective surfaces is a key attribute.',
 'Water resistance or waterproof rating for bathroom, outdoor, or spill-prone items.',
 'Load capacity for shelves, hooks, or storage units indicates strength.',
 'Noise level (e.g., decibels) for appliances like vacuums, fans, or air purifiers.',
 'Light source type (e.g., LED, incandescent, fluorescent) for lighting products.',
 'Thread count for bedding or towels indicates fabric quality.',
 'Pattern or print details for textiles, wallpaper, or decorative items.',
 'Eco-friendly or sustainable attributes (e.g., recycled content, low VOC, bamboo) are increasingly sought after.',
 'Certifications (e.g., Oeko-Tex, UL listed, food-grade, Greenguard) provide assurance.',
 'Portability (e.g., lightweight, foldable, with wheels) for items that need to be moved.',
 'Maintenance frequency (e.g., filter replacement for air purifiers, battery change) for ongoing care.',
 'Ergonomics or comfort level for seating, bedding, or frequently used tools.',
 'Includes a publication date or original release year.',
 'Specifies the number of pages or estimated reading time.',
 'Indicates the physical dimensions (height, width, thickness) and weight for physical copies.',
 'Describes the cover type (e.g., hardcover, paperback, board book, spiral-bound).',
 'Identifies the edition (e.g., first edition, revised edition, special edition, large print edition).',
 'Specifies the language of the content.',
 'Provides a synopsis or blurb summarizing the content.',
 'Further categorizes by specific sub-genre, niche, or academic discipline.',
 'Indicates if it is part of a series and its position within that series.',
 "Features a target audience or age range (e.g., Young Adult, Children's, Adult).",
 'Includes information about awards won or nominations received.',
 'Displays customer reviews and average ratings.',
 'Offers a "Look Inside" or sample chapter feature for preview.',
 'Provides a table of contents for easy navigation.',
 'Mentions if it includes maps, diagrams, photographs, or other visual aids.',
 'Specifies the binding type (e.g., perfect bound, case-bound, saddle-stitched).',
 'Indicates the condition for used or collectible books (e.g., New, Used - Like New, Good, Acceptable).',
 'Lists the translator if the book is a translation.',
 'Identifies the illustrator or photographer if distinct from the author.',
 'Specifies the narrator for audiobook versions.',
 'Details any Digital Rights Management (DRM) restrictions for digital formats.',
 'Provides a reading level or complexity score (e.g., Lexile score).',
 'Includes keywords or tags for search and discovery.',
 'Mentions if it contains a glossary, index, or bibliography.',
 'Highlights any special features like signed copies, limited editions, or bundled content.',
 'Indicates availability status (e.g., In Stock, Pre-order, Out of Print, Backordered).',
 'Lists contributors beyond the main author (e.g., editor, foreword writer).',
 'Specifies the print size or font size, especially for large print editions.',
 'Provides information on regional editions or variations (e.g., US vs. UK edition).',
 'Suggests other books by the same author or similar titles.',
 'Often requires a specific voltage or power input (e.g., 120V AC, 5V DC).',
 'Features specific input/output ports (e.g., USB-C, HDMI, DisplayPort, Ethernet, audio jacks).',
 'Includes a specific operating system, firmware version, or proprietary software.',
 'Battery life or power consumption (e.g., mAh, Wh, Watts) is a key performance metric.',
 'Supports various wireless communication standards (e.g., Wi-Fi 6, Bluetooth 5.0, NFC, 5G).',
 'Display specifications like resolution, size, panel type (e.g., LCD, OLED, AMOLED), and refresh rate are critical.',
 'Often comes with pre-installed software or requires specific applications to function fully.',
 'May require periodic software or firmware updates for optimal performance, security, and new features.',
 'Performance is often measured by benchmarks (e.g., processor speed, graphics rendering capabilities, read/write speeds).',
 'Includes specific camera specifications (e.g., megapixels, aperture, optical zoom, video resolution) for imaging devices.',
 'Audio capabilities are described by speaker quality, headphone support, microphone arrays, and audio codecs.',
 'Often features integrated sensors like accelerometers, gyroscopes, GPS, ambient light sensors, or heart rate monitors.',
 'Storage type and capacity (e.g., SSD, HDD, eMMC, internal memory) are important considerations.',
 'Graphics processing unit (GPU) specifications are crucial for visual performance and gaming.',
 'May offer smart features, AI integration, or voice assistant compatibility (e.g., Alexa, Google Assistant, Siri).',
 'Durability ratings (e.g., IPX water resistance, dust resistance, MIL-STD drop protection) are often highlighted.',
 'Energy efficiency ratings (e.g., Energy Star, EPEAT) are relevant for power consumption and environmental impact.',
 'Comes with specific warranty terms, return policies, and technical support options.',
 'Often requires initial setup, configuration, or pairing with other devices via an app or on-screen prompts.',
 'User interface (UI) and user experience (UX) design (e.g., intuitive navigation, responsiveness) are significant selling points.',
 'May be part of a larger ecosystem of compatible devices, smart home platforms, or cloud services.',
 'Security features (e.g., biometric authentication, encryption, secure boot) are often detailed for data protection.',
 'Physical dimensions, weight, and material construction (e.g., aluminum, plastic, glass) are important for portability and feel.',
 'Includes specific input methods (e.g., touchscreen, physical keyboard, mouse, stylus, trackpad, voice commands).',
 'Often has certifications from regulatory bodies (e.g., FCC, CE, RoHS, UL) for safety and compliance.',
 'May include advanced cooling systems (e.g., fans, heat pipes, liquid cooling) for high-performance devices.',
 'Often designed with specific use cases in mind (e.g., gaming, professional content creation, entertainment, fitness tracking).',
 'Accessories (e.g., chargers, cables, cases, mounts, styluses) are frequently bundled or recommended as add-ons.',
 'Repairability score or availability of spare parts and service manuals can be a factor for product longevity.',
 'Noise levels (e.g., fan noise for computers, hum for power supplies) can be a consideration for user comfort.',
 'Includes specific care instructions, such as washing, drying, and ironing recommendations.',
 'Indicates seasonality, like suitable for summer, winter, or all-season wear.',
 'Specifies the intended occasion or use, such as formal, casual, activewear, or loungewear.',
 'Features the brand or designer name prominently.',
 'Describes the specific style or cut, e.g., A-line, straight leg, bootcut, or wide-leg.',
 'Details the closure type, such as zipper, buttons, snaps, pull-on, or tie-front.',
 'Identifies the neckline style, e.g., V-neck, crew neck, scoop neck, or collared.',
 'Specifies the sleeve length, e.g., short sleeve, long sleeve, sleeveless, or 3/4 sleeve.',
 'Indicates the garment length, e.g., mini, midi, maxi, ankle-length, or crop.',
 'Highlights embellishments or decorative details like embroidery, sequins, ruffles, pleats, or distressed elements.',
 'Mentions the presence or type of lining, e.g., fully lined, unlined, or partial lining.',
 'Describes the stretch or elasticity level, e.g., non-stretch, slight stretch, or high stretch.',
 'Notes sustainability or ethical attributes, such as organic, recycled materials, or fair trade certified.',
 'States the country of origin or manufacturing location.',
 'Belongs to a specific collection or theme, e.g., "Spring 2024 Collection" or "Heritage Line."',
 'Provides a specific fit descriptor, e.g., tailored, oversized, bodycon, or relaxed fit.',
 'Indicates water resistance or waterproofing level for outerwear.',
 'Specifies insulation type or warmth rating for jackets and coats.',
 'Mentions UV protection rating for swimwear or outdoor apparel.',
 'Highlights breathability or moisture-wicking properties for activewear or warm weather garments.',
 "Describes the garment's weight, e.g., lightweight, mid-weight, or heavy-weight.",
 'Details the fabric texture or hand-feel, e.g., soft, smooth, ribbed, brushed, or crisp.',
 'Specifies the type of hardware or accents, e.g., gold-tone buttons, silver-tone zipper, or leather trim.',
 'Describes the pocket configuration, e.g., number of pockets, type like patch pockets, or slit pockets.',
 'Identifies the waist style, e.g., high-waisted, mid-rise, low-rise, or elasticated waist.',
 'Details the collar style, e.g., point collar, spread collar, stand collar, or Peter Pan collar.',
 'Specifies the pattern type, e.g., floral print, striped, plaid, polka dot, or animal print.',
 'Indicates the intended activity or sport, e.g., yoga, running, hiking, or swimming.',
 'Clarifies if the product is sold as a set or an individual item, e.g., a two-piece set or an individual top.',
 'Describes layering capability or design, e.g., designed for layering or suitable as an outer layer.']



# stackoverflow = [
#     "Uses clear and concise language, avoiding jargon unless necessary and explaining it when used.",
#     "The question demonstrates a clear understanding of the problem domain, showing prior research.",
#     "Includes a minimal, reproducible example (a \"minimal, reproducible example\" or MRE).",
#     "The code is properly indented and easy to read, following standard coding style guidelines.",
#     "The question title is specific, descriptive, and accurately reflects the problem.",
#     "The question avoids subjective phrasing or opinion-based requests; it focuses on a technical issue.",
#     "The question clearly defines what the expected output or behavior should be.",
#     "The question clarifies any assumptions or constraints relevant to the problem.",
#     "Contains a clear explanation of what the user has already tried to solve the issue.",
#     "Mentions the specific libraries, frameworks, or technologies involved (with versions if relevant).",
#     "Includes the operating system and the environment being used (e.g., browser, IDE, command line).",
#     "The problem is well-scoped, addressing a single, focused issue.",
#     "Demonstrates an understanding of the fundamental concepts involved, showing effort to learn.",
#     "The question avoids overly complex or convoluted code snippets that obscure the core issue.",
#     "The question is not a duplicate of an existing, well-answered question (searched beforehand).",
#     "The formatting of the question is clean and readable (e.g., bullet points, numbered lists when helpful).",
#     "The question is written in a professional and respectful tone.",
#     "The code examples are runnable without significant modification.",
#     "The question provides sufficient background information to understand the context.",
#     "The question includes links to relevant documentation or resources.",
#     "The question uses appropriate markdown formatting for code, lists, and emphasis.",
#     "The problem is not trivial and presents a genuine challenge or learning opportunity.",
#     "The question is well-structured and easy to follow.",
#     "The question demonstrates a willingness to learn and improve.",
#     "The question avoids general \"how do I\" type of requests.",
#     "The question clearly identifies the part of the code that is problematic.",
#     "The question highlights what the user has already tried and the results of those attempts.",
#     "Includes links to any relevant online resources or tutorials the user has already consulted.",
#     "The question demonstrates an understanding of the underlying concepts being used.",
#     "The question is not seeking a solution that circumvents established best practices.",
#     "The question body contains significant grammatical errors or spelling mistakes that are subsequently corrected.",
#     "The question title is unclear, too broad, or lacks relevant keywords, and is later improved.",
#     "The code snippets provided are initially unformatted, making them difficult to read and understand.",
#     "The code snippets provided are initially incomplete or contain errors that are later corrected through edits.",
#     "The question is initially perceived as a \"homework dump\" or a request for a complete solution.",
#     "The original question uses overly informal language or slang, which is then refined to a more professional tone.",
#     "The question fails to provide context, such as the programming language or framework being used, which is later added.",
#     "The question lacks a clear problem statement, and the edit history shows attempts to clarify the user's intent.",
#     "The original author's understanding of the concepts is flawed, and the edits reflect attempts to correct misconceptions.",
#     "The question receives downvotes soon after posting, indicating immediate quality concerns.",
#     "The question is marked as a duplicate, but the edits aim to differentiate it or provide additional context.",
#     "The question includes irrelevant information or extraneous details that are subsequently removed.",
#     "The question struggles to articulate the specific error message encountered, prompting others to help clarify it.",
#     "The formatting uses inconsistent or improper use of markdown, and is corrected through edits.",
#     "The question references external resources or documentation improperly, and the edits provide proper links or citations.",
#     "The question is initially closed (e.g., as \"off-topic\" or \"unclear\") but is later re-opened after edits to improve clarity and scope.",
#     "The author includes personal opinions or subjective statements that are edited for objectivity.",
#     "The original question lacks a minimal, reproducible example (a \"working example\"), and this is subsequently provided.",
#     "The original author does not include what they have already tried, causing other users to provide general answers.",
#     "The author does not provide system information (OS, environment details) required to effectively solve the problem, which is subsequently added.",
#     "The edits reveal a misunderstanding of best practices within the programming community.",
#     "The edits include significant refactoring of the code to increase readability or clarity.",
#     "The question's initial tags are excessively broad or irrelevant, replaced with tags reflecting the actual topic of the question.",
#     "The edit history reveals the iterative refinement of the question based on feedback from other users.",
#     "The edits show the inclusion of missing imports or dependency declarations.",
#     "The initial answer (if any) indicates misunderstandings and the edits work to clarify it.",
#     "The question is missing a complete, self-contained code example, that is later provided after editing.",
#     "The question starts with a greeting or closing remark instead of the actual problem statement, and this is removed.",
#     "The edits address security concerns that were present in the original code example.",
#     "The question is heavily upvoted by other users, and the edits take advantage of this attention to re-iterate the best answer to the problem.",
#     "` format.\n\n<example>Contains significant spelling, grammar, or punctuation errors, making it difficult to understand.",
#     "Uses excessively informal language, slang, or emojis, detracting from professional communication.",
#     "The question title is vague, uninformative, or missing entirely.",
#     "The body of the question lacks context or background information about the problem.",
#     "Fails to include any code snippets, even when relevant to the question.",
#     "The code snippets are poorly formatted, making them hard to read and analyze (e.g., no indentation).",
#     "The code contains obvious errors that should have been caught during initial testing.",
#     "The question provides no attempts to solve the problem, showing a lack of research effort.",
#     "Shows signs of being a \"homework dump,\" where the user is just posting an assignment question.",
#     "The question is overly verbose, rambling, or includes unnecessary details.",
#     "The question is highly localized to a specific, unique setup, with no general applicability.",
#     "Focuses on a library or framework known to be outdated or no longer supported.",
#     "Duplicates an existing question that is easily found through a simple search.",
#     "Asks questions that are primarily opinion-based or debateable, instead of factual.",
#     "The question is too broad in scope, tackling multiple unrelated issues in one post.",
#     "The user demonstrates a lack of understanding of fundamental programming concepts.",
#     "The question's tone is demanding, rude, or shows a lack of respect for the community.",
#     "The question is off-topic for Stack Overflow (e.g., related to general computer usage, not programming).",
#     "The question is about a topic that is considered inherently dangerous or irresponsible (e.g., malicious code).",
#     "The question has been edited multiple times, but the core issue of quality remains.",
#     "The question is unclear about the actual problem; the user hasn't clearly stated their issue.",
#     "The user has a low reputation score, often indicating a new or infrequent contributor.",
#     "The user has a history of asking low-quality questions (seen through profile activity).",
#     "The question includes sensitive information like API keys or passwords, compromising security.",
#     "The question does not specify the programming language or environment being used.",
#     "The question lacks clear and concise problem description, using vague language.",
#     "The code in the question is not compilable or runnable as presented.",
#     "The user is asking for debugging help without providing debugging attempts or error messages.",
#     "The question attempts to solve an extremely complex problem with a simple, naive approach.",
#     "The question's phrasing strongly suggests a lack of prior research or effort made by the asker."
# ]

stackoverflow = [
    "aabbbcc1", "aabbbcc2", "aabbbcc3", "aabbbcc4", "aabbbcc5",
    "aabbbcc6", "aabbbcc7", "aabbbcc8", "aabbbcc9", "aabbbcc10",
    "aabbbcc11", "aabbbcc12", "aabbbcc13", "aabbbcc14", "aabbbcc15",
    "aabbbcc16", "aabbbcc17", "aabbbcc18", "aabbbcc19", "aabbbcc20",
    "aabbbcc21", "aabbbcc22", "aabbbcc23", "aabbbcc24", "aabbbcc25",
    "aabbbcc26", "aabbbcc27", "aabbbcc28", "aabbbcc29", "aabbbcc30",
    "aabbbcc31", "aabbbcc32", "aabbbcc33", "aabbbcc34", "aabbbcc35",
    "aabbbcc36", "aabbbcc37", "aabbbcc38", "aabbbcc39", "aabbbcc40",
    "aabbbcc41", "aabbbcc42", "aabbbcc43", "aabbbcc44", "aabbbcc45",
    "aabbbcc46", "aabbbcc47", "aabbbcc48", "aabbbcc49", "aabbbcc50",
    "aabbbcc51", "aabbbcc52", "aabbbcc53", "aabbbcc54", "aabbbcc55",
    "aabbbcc56", "aabbbcc57", "aabbbcc58", "aabbbcc59", "aabbbcc60",
    "aabbbcc61", "aabbbcc62", "aabbbcc63", "aabbbcc64", "aabbbcc65",
    "aabbbcc66", "aabbbcc67", "aabbbcc68", "aabbbcc69", "aabbbcc70",
    "aabbbcc71", "aabbbcc72", "aabbbcc73", "aabbbcc74", "aabbbcc75",
    "aabbbcc76", "aabbbcc77", "aabbbcc78", "aabbbcc79", "aabbbcc80",
    "aabbbcc81", "aabbbcc82", "aabbbcc83", "aabbbcc84", "aabbbcc85",
    "aabbbcc86", "aabbbcc87", "aabbbcc88", "aabbbcc89", "aabbbcc90"
]